[package]
name = "jarl"
version = "1.0.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
bounded-vec-deque = "0.1.1"
tokio = { version = "1.48.0", features = ["full"] }
clap = { version = "4.5.53", features = ["derive"] }
